BEGIN;
SELECT setval(pg_get_serial_sequence('"accounts_user_groups"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "accounts_user_groups";
SELECT setval(pg_get_serial_sequence('"accounts_user_user_permissions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "accounts_user_user_permissions";
SELECT setval(pg_get_serial_sequence('"accounts_user"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "accounts_user";
SELECT setval(pg_get_serial_sequence('"activities_activity_favorited_by"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "activities_activity_favorited_by";
SELECT setval(pg_get_serial_sequence('"activities_activity"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "activities_activity";
SELECT setval(pg_get_serial_sequence('"trips_trip_favorited_by"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "trips_trip_favorited_by";
SELECT setval(pg_get_serial_sequence('"trips_trip"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "trips_trip";
SELECT setval(pg_get_serial_sequence('"trips_tripstop"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "trips_tripstop";
SELECT setval(pg_get_serial_sequence('"trips_itineraryactivity"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "trips_itineraryactivity";
SELECT setval(pg_get_serial_sequence('"budgets_expense"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "budgets_expense";
SELECT setval(pg_get_serial_sequence('"destinations_destination_favorited_by"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "destinations_destination_favorited_by";
SELECT setval(pg_get_serial_sequence('"destinations_destination"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "destinations_destination";
SELECT setval(pg_get_serial_sequence('"auth_permission"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_permission";
SELECT setval(pg_get_serial_sequence('"auth_group_permissions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_group_permissions";
SELECT setval(pg_get_serial_sequence('"auth_group"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_group";
SELECT setval(pg_get_serial_sequence('"django_admin_log"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_admin_log";
SELECT setval(pg_get_serial_sequence('"token_blacklist_outstandingtoken"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "token_blacklist_outstandingtoken";
SELECT setval(pg_get_serial_sequence('"token_blacklist_blacklistedtoken"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "token_blacklist_blacklistedtoken";
SELECT setval(pg_get_serial_sequence('"django_content_type"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_content_type";
COMMIT;
