# Generated by Django 5.0.7 on 2026-08-22 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Sightseeing', 'Sightseeing'), ('Food', 'Food'), ('Adventure', 'Adventure'), ('Shopping', 'Shopping'), ('Culture', 'Culture'), ('Nature', 'Nature'), ('Nightlife', 'Nightlife'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], db_index=True, max_length=30)),
                ('image', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city__city_name', 'name'],
                'indexes': [models.Index(fields=['category', 'estimated_cost'], name='activities__categor_1e12a3_idx')],
            },
        ),
    ]
