# Generated by Django 5.0.7 on 2026-08-22 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=120)),
                ('country', models.CharField(db_index=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cost_index', models.PositiveIntegerField(default=50)),
                ('popularity_score', models.PositiveIntegerField(default=50)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_cities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city_name'],
                'indexes': [models.Index(fields=['city_name', 'country'], name='destination_city_na_753177_idx')],
            },
        ),
    ]
